language: go

go:
  - 1.20
os:
  - linux
env:
  global:
    - GO111MODULE=on
branches:
  only:
    - main
before_install:
  - echo -e "machine github.com\n  login $GIT_TOKEN" > ~/.netrc
  - chmod 600 ~/.netrc
install: true
before_script:
  - go mod tidy
  - go get -u github.com/onsi/ginkgo/v2
  - go install github.com/onsi/ginkgo/v2/ginkgo
  - go get -u github.com/onsi/gomega/...
script:
  - test/coverage.sh