// Code generated by counterfeiter. DO NOT EDIT.
package groupsfakes

import (
	"sync"

	"github.com/IBM/satcon-client-go/client/actions/groups"
	"github.com/IBM/satcon-client-go/client/types"
)

type FakeGroupService struct {
	AddGroupStub        func(string, string) (*groups.AddGroupResponseDataDetails, error)
	addGroupMutex       sync.RWMutex
	addGroupArgsForCall []struct {
		arg1 string
		arg2 string
	}
	addGroupReturns struct {
		result1 *groups.AddGroupResponseDataDetails
		result2 error
	}
	addGroupReturnsOnCall map[int]struct {
		result1 *groups.AddGroupResponseDataDetails
		result2 error
	}
	GroupClustersStub        func(string, string, []string) (*groups.GroupClustersResponseDataDetails, error)
	groupClustersMutex       sync.RWMutex
	groupClustersArgsForCall []struct {
		arg1 string
		arg2 string
		arg3 []string
	}
	groupClustersReturns struct {
		result1 *groups.GroupClustersResponseDataDetails
		result2 error
	}
	groupClustersReturnsOnCall map[int]struct {
		result1 *groups.GroupClustersResponseDataDetails
		result2 error
	}
	GroupsStub        func(string) (types.GroupList, error)
	groupsMutex       sync.RWMutex
	groupsArgsForCall []struct {
		arg1 string
	}
	groupsReturns struct {
		result1 types.GroupList
		result2 error
	}
	groupsReturnsOnCall map[int]struct {
		result1 types.GroupList
		result2 error
	}
	RemoveGroupStub        func(string, string) (*groups.RemoveGroupResponseDataDetails, error)
	removeGroupMutex       sync.RWMutex
	removeGroupArgsForCall []struct {
		arg1 string
		arg2 string
	}
	removeGroupReturns struct {
		result1 *groups.RemoveGroupResponseDataDetails
		result2 error
	}
	removeGroupReturnsOnCall map[int]struct {
		result1 *groups.RemoveGroupResponseDataDetails
		result2 error
	}
	RemoveGroupByNameStub        func(string, string) (*groups.RemoveGroupByNameResponseDataDetails, error)
	removeGroupByNameMutex       sync.RWMutex
	removeGroupByNameArgsForCall []struct {
		arg1 string
		arg2 string
	}
	removeGroupByNameReturns struct {
		result1 *groups.RemoveGroupByNameResponseDataDetails
		result2 error
	}
	removeGroupByNameReturnsOnCall map[int]struct {
		result1 *groups.RemoveGroupByNameResponseDataDetails
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeGroupService) AddGroup(arg1 string, arg2 string) (*groups.AddGroupResponseDataDetails, error) {
	fake.addGroupMutex.Lock()
	ret, specificReturn := fake.addGroupReturnsOnCall[len(fake.addGroupArgsForCall)]
	fake.addGroupArgsForCall = append(fake.addGroupArgsForCall, struct {
		arg1 string
		arg2 string
	}{arg1, arg2})
	stub := fake.AddGroupStub
	fakeReturns := fake.addGroupReturns
	fake.recordInvocation("AddGroup", []interface{}{arg1, arg2})
	fake.addGroupMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeGroupService) AddGroupCallCount() int {
	fake.addGroupMutex.RLock()
	defer fake.addGroupMutex.RUnlock()
	return len(fake.addGroupArgsForCall)
}

func (fake *FakeGroupService) AddGroupCalls(stub func(string, string) (*groups.AddGroupResponseDataDetails, error)) {
	fake.addGroupMutex.Lock()
	defer fake.addGroupMutex.Unlock()
	fake.AddGroupStub = stub
}

func (fake *FakeGroupService) AddGroupArgsForCall(i int) (string, string) {
	fake.addGroupMutex.RLock()
	defer fake.addGroupMutex.RUnlock()
	argsForCall := fake.addGroupArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeGroupService) AddGroupReturns(result1 *groups.AddGroupResponseDataDetails, result2 error) {
	fake.addGroupMutex.Lock()
	defer fake.addGroupMutex.Unlock()
	fake.AddGroupStub = nil
	fake.addGroupReturns = struct {
		result1 *groups.AddGroupResponseDataDetails
		result2 error
	}{result1, result2}
}

func (fake *FakeGroupService) AddGroupReturnsOnCall(i int, result1 *groups.AddGroupResponseDataDetails, result2 error) {
	fake.addGroupMutex.Lock()
	defer fake.addGroupMutex.Unlock()
	fake.AddGroupStub = nil
	if fake.addGroupReturnsOnCall == nil {
		fake.addGroupReturnsOnCall = make(map[int]struct {
			result1 *groups.AddGroupResponseDataDetails
			result2 error
		})
	}
	fake.addGroupReturnsOnCall[i] = struct {
		result1 *groups.AddGroupResponseDataDetails
		result2 error
	}{result1, result2}
}

func (fake *FakeGroupService) GroupClusters(arg1 string, arg2 string, arg3 []string) (*groups.GroupClustersResponseDataDetails, error) {
	var arg3Copy []string
	if arg3 != nil {
		arg3Copy = make([]string, len(arg3))
		copy(arg3Copy, arg3)
	}
	fake.groupClustersMutex.Lock()
	ret, specificReturn := fake.groupClustersReturnsOnCall[len(fake.groupClustersArgsForCall)]
	fake.groupClustersArgsForCall = append(fake.groupClustersArgsForCall, struct {
		arg1 string
		arg2 string
		arg3 []string
	}{arg1, arg2, arg3Copy})
	stub := fake.GroupClustersStub
	fakeReturns := fake.groupClustersReturns
	fake.recordInvocation("GroupClusters", []interface{}{arg1, arg2, arg3Copy})
	fake.groupClustersMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeGroupService) GroupClustersCallCount() int {
	fake.groupClustersMutex.RLock()
	defer fake.groupClustersMutex.RUnlock()
	return len(fake.groupClustersArgsForCall)
}

func (fake *FakeGroupService) GroupClustersCalls(stub func(string, string, []string) (*groups.GroupClustersResponseDataDetails, error)) {
	fake.groupClustersMutex.Lock()
	defer fake.groupClustersMutex.Unlock()
	fake.GroupClustersStub = stub
}

func (fake *FakeGroupService) GroupClustersArgsForCall(i int) (string, string, []string) {
	fake.groupClustersMutex.RLock()
	defer fake.groupClustersMutex.RUnlock()
	argsForCall := fake.groupClustersArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeGroupService) GroupClustersReturns(result1 *groups.GroupClustersResponseDataDetails, result2 error) {
	fake.groupClustersMutex.Lock()
	defer fake.groupClustersMutex.Unlock()
	fake.GroupClustersStub = nil
	fake.groupClustersReturns = struct {
		result1 *groups.GroupClustersResponseDataDetails
		result2 error
	}{result1, result2}
}

func (fake *FakeGroupService) GroupClustersReturnsOnCall(i int, result1 *groups.GroupClustersResponseDataDetails, result2 error) {
	fake.groupClustersMutex.Lock()
	defer fake.groupClustersMutex.Unlock()
	fake.GroupClustersStub = nil
	if fake.groupClustersReturnsOnCall == nil {
		fake.groupClustersReturnsOnCall = make(map[int]struct {
			result1 *groups.GroupClustersResponseDataDetails
			result2 error
		})
	}
	fake.groupClustersReturnsOnCall[i] = struct {
		result1 *groups.GroupClustersResponseDataDetails
		result2 error
	}{result1, result2}
}

func (fake *FakeGroupService) Groups(arg1 string) (types.GroupList, error) {
	fake.groupsMutex.Lock()
	ret, specificReturn := fake.groupsReturnsOnCall[len(fake.groupsArgsForCall)]
	fake.groupsArgsForCall = append(fake.groupsArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.GroupsStub
	fakeReturns := fake.groupsReturns
	fake.recordInvocation("Groups", []interface{}{arg1})
	fake.groupsMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeGroupService) GroupsCallCount() int {
	fake.groupsMutex.RLock()
	defer fake.groupsMutex.RUnlock()
	return len(fake.groupsArgsForCall)
}

func (fake *FakeGroupService) GroupsCalls(stub func(string) (types.GroupList, error)) {
	fake.groupsMutex.Lock()
	defer fake.groupsMutex.Unlock()
	fake.GroupsStub = stub
}

func (fake *FakeGroupService) GroupsArgsForCall(i int) string {
	fake.groupsMutex.RLock()
	defer fake.groupsMutex.RUnlock()
	argsForCall := fake.groupsArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeGroupService) GroupsReturns(result1 types.GroupList, result2 error) {
	fake.groupsMutex.Lock()
	defer fake.groupsMutex.Unlock()
	fake.GroupsStub = nil
	fake.groupsReturns = struct {
		result1 types.GroupList
		result2 error
	}{result1, result2}
}

func (fake *FakeGroupService) GroupsReturnsOnCall(i int, result1 types.GroupList, result2 error) {
	fake.groupsMutex.Lock()
	defer fake.groupsMutex.Unlock()
	fake.GroupsStub = nil
	if fake.groupsReturnsOnCall == nil {
		fake.groupsReturnsOnCall = make(map[int]struct {
			result1 types.GroupList
			result2 error
		})
	}
	fake.groupsReturnsOnCall[i] = struct {
		result1 types.GroupList
		result2 error
	}{result1, result2}
}

func (fake *FakeGroupService) RemoveGroup(arg1 string, arg2 string) (*groups.RemoveGroupResponseDataDetails, error) {
	fake.removeGroupMutex.Lock()
	ret, specificReturn := fake.removeGroupReturnsOnCall[len(fake.removeGroupArgsForCall)]
	fake.removeGroupArgsForCall = append(fake.removeGroupArgsForCall, struct {
		arg1 string
		arg2 string
	}{arg1, arg2})
	stub := fake.RemoveGroupStub
	fakeReturns := fake.removeGroupReturns
	fake.recordInvocation("RemoveGroup", []interface{}{arg1, arg2})
	fake.removeGroupMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeGroupService) RemoveGroupCallCount() int {
	fake.removeGroupMutex.RLock()
	defer fake.removeGroupMutex.RUnlock()
	return len(fake.removeGroupArgsForCall)
}

func (fake *FakeGroupService) RemoveGroupCalls(stub func(string, string) (*groups.RemoveGroupResponseDataDetails, error)) {
	fake.removeGroupMutex.Lock()
	defer fake.removeGroupMutex.Unlock()
	fake.RemoveGroupStub = stub
}

func (fake *FakeGroupService) RemoveGroupArgsForCall(i int) (string, string) {
	fake.removeGroupMutex.RLock()
	defer fake.removeGroupMutex.RUnlock()
	argsForCall := fake.removeGroupArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeGroupService) RemoveGroupReturns(result1 *groups.RemoveGroupResponseDataDetails, result2 error) {
	fake.removeGroupMutex.Lock()
	defer fake.removeGroupMutex.Unlock()
	fake.RemoveGroupStub = nil
	fake.removeGroupReturns = struct {
		result1 *groups.RemoveGroupResponseDataDetails
		result2 error
	}{result1, result2}
}

func (fake *FakeGroupService) RemoveGroupReturnsOnCall(i int, result1 *groups.RemoveGroupResponseDataDetails, result2 error) {
	fake.removeGroupMutex.Lock()
	defer fake.removeGroupMutex.Unlock()
	fake.RemoveGroupStub = nil
	if fake.removeGroupReturnsOnCall == nil {
		fake.removeGroupReturnsOnCall = make(map[int]struct {
			result1 *groups.RemoveGroupResponseDataDetails
			result2 error
		})
	}
	fake.removeGroupReturnsOnCall[i] = struct {
		result1 *groups.RemoveGroupResponseDataDetails
		result2 error
	}{result1, result2}
}

func (fake *FakeGroupService) RemoveGroupByName(arg1 string, arg2 string) (*groups.RemoveGroupByNameResponseDataDetails, error) {
	fake.removeGroupByNameMutex.Lock()
	ret, specificReturn := fake.removeGroupByNameReturnsOnCall[len(fake.removeGroupByNameArgsForCall)]
	fake.removeGroupByNameArgsForCall = append(fake.removeGroupByNameArgsForCall, struct {
		arg1 string
		arg2 string
	}{arg1, arg2})
	stub := fake.RemoveGroupByNameStub
	fakeReturns := fake.removeGroupByNameReturns
	fake.recordInvocation("RemoveGroupByName", []interface{}{arg1, arg2})
	fake.removeGroupByNameMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeGroupService) RemoveGroupByNameCallCount() int {
	fake.removeGroupByNameMutex.RLock()
	defer fake.removeGroupByNameMutex.RUnlock()
	return len(fake.removeGroupByNameArgsForCall)
}

func (fake *FakeGroupService) RemoveGroupByNameCalls(stub func(string, string) (*groups.RemoveGroupByNameResponseDataDetails, error)) {
	fake.removeGroupByNameMutex.Lock()
	defer fake.removeGroupByNameMutex.Unlock()
	fake.RemoveGroupByNameStub = stub
}

func (fake *FakeGroupService) RemoveGroupByNameArgsForCall(i int) (string, string) {
	fake.removeGroupByNameMutex.RLock()
	defer fake.removeGroupByNameMutex.RUnlock()
	argsForCall := fake.removeGroupByNameArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeGroupService) RemoveGroupByNameReturns(result1 *groups.RemoveGroupByNameResponseDataDetails, result2 error) {
	fake.removeGroupByNameMutex.Lock()
	defer fake.removeGroupByNameMutex.Unlock()
	fake.RemoveGroupByNameStub = nil
	fake.removeGroupByNameReturns = struct {
		result1 *groups.RemoveGroupByNameResponseDataDetails
		result2 error
	}{result1, result2}
}

func (fake *FakeGroupService) RemoveGroupByNameReturnsOnCall(i int, result1 *groups.RemoveGroupByNameResponseDataDetails, result2 error) {
	fake.removeGroupByNameMutex.Lock()
	defer fake.removeGroupByNameMutex.Unlock()
	fake.RemoveGroupByNameStub = nil
	if fake.removeGroupByNameReturnsOnCall == nil {
		fake.removeGroupByNameReturnsOnCall = make(map[int]struct {
			result1 *groups.RemoveGroupByNameResponseDataDetails
			result2 error
		})
	}
	fake.removeGroupByNameReturnsOnCall[i] = struct {
		result1 *groups.RemoveGroupByNameResponseDataDetails
		result2 error
	}{result1, result2}
}

func (fake *FakeGroupService) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.addGroupMutex.RLock()
	defer fake.addGroupMutex.RUnlock()
	fake.groupClustersMutex.RLock()
	defer fake.groupClustersMutex.RUnlock()
	fake.groupsMutex.RLock()
	defer fake.groupsMutex.RUnlock()
	fake.removeGroupMutex.RLock()
	defer fake.removeGroupMutex.RUnlock()
	fake.removeGroupByNameMutex.RLock()
	defer fake.removeGroupByNameMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeGroupService) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ groups.GroupService = new(FakeGroupService)
