// Code generated by counterfeiter. DO NOT EDIT.
package resourcesfakes

import (
	"sync"

	"github.com/IBM/satcon-client-go/client/actions/resources"
	"github.com/IBM/satcon-client-go/client/types"
)

type FakeResourceService struct {
	ResourceContentStub        func(string, string, string) (*types.ResourceContentObj, error)
	resourceContentMutex       sync.RWMutex
	resourceContentArgsForCall []struct {
		arg1 string
		arg2 string
		arg3 string
	}
	resourceContentReturns struct {
		result1 *types.ResourceContentObj
		result2 error
	}
	resourceContentReturnsOnCall map[int]struct {
		result1 *types.ResourceContentObj
		result2 error
	}
	ResourcesStub        func(types.ResourcesParams) (*types.ResourceList, error)
	resourcesMutex       sync.RWMutex
	resourcesArgsForCall []struct {
		arg1 types.ResourcesParams
	}
	resourcesReturns struct {
		result1 *types.ResourceList
		result2 error
	}
	resourcesReturnsOnCall map[int]struct {
		result1 *types.ResourceList
		result2 error
	}
	ResourcesByClusterStub        func(string, string, string, int, *types.Resource) (*types.ResourceList, error)
	resourcesByClusterMutex       sync.RWMutex
	resourcesByClusterArgsForCall []struct {
		arg1 string
		arg2 string
		arg3 string
		arg4 int
		arg5 *types.Resource
	}
	resourcesByClusterReturns struct {
		result1 *types.ResourceList
		result2 error
	}
	resourcesByClusterReturnsOnCall map[int]struct {
		result1 *types.ResourceList
		result2 error
	}
	ResourcesByOrgIDStub        func(string) (*types.ResourceList, error)
	resourcesByOrgIDMutex       sync.RWMutex
	resourcesByOrgIDArgsForCall []struct {
		arg1 string
	}
	resourcesByOrgIDReturns struct {
		result1 *types.ResourceList
		result2 error
	}
	resourcesByOrgIDReturnsOnCall map[int]struct {
		result1 *types.ResourceList
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeResourceService) ResourceContent(arg1 string, arg2 string, arg3 string) (*types.ResourceContentObj, error) {
	fake.resourceContentMutex.Lock()
	ret, specificReturn := fake.resourceContentReturnsOnCall[len(fake.resourceContentArgsForCall)]
	fake.resourceContentArgsForCall = append(fake.resourceContentArgsForCall, struct {
		arg1 string
		arg2 string
		arg3 string
	}{arg1, arg2, arg3})
	stub := fake.ResourceContentStub
	fakeReturns := fake.resourceContentReturns
	fake.recordInvocation("ResourceContent", []interface{}{arg1, arg2, arg3})
	fake.resourceContentMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeResourceService) ResourceContentCallCount() int {
	fake.resourceContentMutex.RLock()
	defer fake.resourceContentMutex.RUnlock()
	return len(fake.resourceContentArgsForCall)
}

func (fake *FakeResourceService) ResourceContentCalls(stub func(string, string, string) (*types.ResourceContentObj, error)) {
	fake.resourceContentMutex.Lock()
	defer fake.resourceContentMutex.Unlock()
	fake.ResourceContentStub = stub
}

func (fake *FakeResourceService) ResourceContentArgsForCall(i int) (string, string, string) {
	fake.resourceContentMutex.RLock()
	defer fake.resourceContentMutex.RUnlock()
	argsForCall := fake.resourceContentArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeResourceService) ResourceContentReturns(result1 *types.ResourceContentObj, result2 error) {
	fake.resourceContentMutex.Lock()
	defer fake.resourceContentMutex.Unlock()
	fake.ResourceContentStub = nil
	fake.resourceContentReturns = struct {
		result1 *types.ResourceContentObj
		result2 error
	}{result1, result2}
}

func (fake *FakeResourceService) ResourceContentReturnsOnCall(i int, result1 *types.ResourceContentObj, result2 error) {
	fake.resourceContentMutex.Lock()
	defer fake.resourceContentMutex.Unlock()
	fake.ResourceContentStub = nil
	if fake.resourceContentReturnsOnCall == nil {
		fake.resourceContentReturnsOnCall = make(map[int]struct {
			result1 *types.ResourceContentObj
			result2 error
		})
	}
	fake.resourceContentReturnsOnCall[i] = struct {
		result1 *types.ResourceContentObj
		result2 error
	}{result1, result2}
}

func (fake *FakeResourceService) Resources(arg1 types.ResourcesParams) (*types.ResourceList, error) {
	fake.resourcesMutex.Lock()
	ret, specificReturn := fake.resourcesReturnsOnCall[len(fake.resourcesArgsForCall)]
	fake.resourcesArgsForCall = append(fake.resourcesArgsForCall, struct {
		arg1 types.ResourcesParams
	}{arg1})
	stub := fake.ResourcesStub
	fakeReturns := fake.resourcesReturns
	fake.recordInvocation("Resources", []interface{}{arg1})
	fake.resourcesMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeResourceService) ResourcesCallCount() int {
	fake.resourcesMutex.RLock()
	defer fake.resourcesMutex.RUnlock()
	return len(fake.resourcesArgsForCall)
}

func (fake *FakeResourceService) ResourcesCalls(stub func(types.ResourcesParams) (*types.ResourceList, error)) {
	fake.resourcesMutex.Lock()
	defer fake.resourcesMutex.Unlock()
	fake.ResourcesStub = stub
}

func (fake *FakeResourceService) ResourcesArgsForCall(i int) types.ResourcesParams {
	fake.resourcesMutex.RLock()
	defer fake.resourcesMutex.RUnlock()
	argsForCall := fake.resourcesArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeResourceService) ResourcesReturns(result1 *types.ResourceList, result2 error) {
	fake.resourcesMutex.Lock()
	defer fake.resourcesMutex.Unlock()
	fake.ResourcesStub = nil
	fake.resourcesReturns = struct {
		result1 *types.ResourceList
		result2 error
	}{result1, result2}
}

func (fake *FakeResourceService) ResourcesReturnsOnCall(i int, result1 *types.ResourceList, result2 error) {
	fake.resourcesMutex.Lock()
	defer fake.resourcesMutex.Unlock()
	fake.ResourcesStub = nil
	if fake.resourcesReturnsOnCall == nil {
		fake.resourcesReturnsOnCall = make(map[int]struct {
			result1 *types.ResourceList
			result2 error
		})
	}
	fake.resourcesReturnsOnCall[i] = struct {
		result1 *types.ResourceList
		result2 error
	}{result1, result2}
}

func (fake *FakeResourceService) ResourcesByCluster(arg1 string, arg2 string, arg3 string, arg4 int, arg5 *types.Resource) (*types.ResourceList, error) {
	fake.resourcesByClusterMutex.Lock()
	ret, specificReturn := fake.resourcesByClusterReturnsOnCall[len(fake.resourcesByClusterArgsForCall)]
	fake.resourcesByClusterArgsForCall = append(fake.resourcesByClusterArgsForCall, struct {
		arg1 string
		arg2 string
		arg3 string
		arg4 int
		arg5 *types.Resource
	}{arg1, arg2, arg3, arg4, arg5})
	stub := fake.ResourcesByClusterStub
	fakeReturns := fake.resourcesByClusterReturns
	fake.recordInvocation("ResourcesByCluster", []interface{}{arg1, arg2, arg3, arg4, arg5})
	fake.resourcesByClusterMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4, arg5)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeResourceService) ResourcesByClusterCallCount() int {
	fake.resourcesByClusterMutex.RLock()
	defer fake.resourcesByClusterMutex.RUnlock()
	return len(fake.resourcesByClusterArgsForCall)
}

func (fake *FakeResourceService) ResourcesByClusterCalls(stub func(string, string, string, int, *types.Resource) (*types.ResourceList, error)) {
	fake.resourcesByClusterMutex.Lock()
	defer fake.resourcesByClusterMutex.Unlock()
	fake.ResourcesByClusterStub = stub
}

func (fake *FakeResourceService) ResourcesByClusterArgsForCall(i int) (string, string, string, int, *types.Resource) {
	fake.resourcesByClusterMutex.RLock()
	defer fake.resourcesByClusterMutex.RUnlock()
	argsForCall := fake.resourcesByClusterArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4, argsForCall.arg5
}

func (fake *FakeResourceService) ResourcesByClusterReturns(result1 *types.ResourceList, result2 error) {
	fake.resourcesByClusterMutex.Lock()
	defer fake.resourcesByClusterMutex.Unlock()
	fake.ResourcesByClusterStub = nil
	fake.resourcesByClusterReturns = struct {
		result1 *types.ResourceList
		result2 error
	}{result1, result2}
}

func (fake *FakeResourceService) ResourcesByClusterReturnsOnCall(i int, result1 *types.ResourceList, result2 error) {
	fake.resourcesByClusterMutex.Lock()
	defer fake.resourcesByClusterMutex.Unlock()
	fake.ResourcesByClusterStub = nil
	if fake.resourcesByClusterReturnsOnCall == nil {
		fake.resourcesByClusterReturnsOnCall = make(map[int]struct {
			result1 *types.ResourceList
			result2 error
		})
	}
	fake.resourcesByClusterReturnsOnCall[i] = struct {
		result1 *types.ResourceList
		result2 error
	}{result1, result2}
}

func (fake *FakeResourceService) ResourcesByOrgID(arg1 string) (*types.ResourceList, error) {
	fake.resourcesByOrgIDMutex.Lock()
	ret, specificReturn := fake.resourcesByOrgIDReturnsOnCall[len(fake.resourcesByOrgIDArgsForCall)]
	fake.resourcesByOrgIDArgsForCall = append(fake.resourcesByOrgIDArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.ResourcesByOrgIDStub
	fakeReturns := fake.resourcesByOrgIDReturns
	fake.recordInvocation("ResourcesByOrgID", []interface{}{arg1})
	fake.resourcesByOrgIDMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeResourceService) ResourcesByOrgIDCallCount() int {
	fake.resourcesByOrgIDMutex.RLock()
	defer fake.resourcesByOrgIDMutex.RUnlock()
	return len(fake.resourcesByOrgIDArgsForCall)
}

func (fake *FakeResourceService) ResourcesByOrgIDCalls(stub func(string) (*types.ResourceList, error)) {
	fake.resourcesByOrgIDMutex.Lock()
	defer fake.resourcesByOrgIDMutex.Unlock()
	fake.ResourcesByOrgIDStub = stub
}

func (fake *FakeResourceService) ResourcesByOrgIDArgsForCall(i int) string {
	fake.resourcesByOrgIDMutex.RLock()
	defer fake.resourcesByOrgIDMutex.RUnlock()
	argsForCall := fake.resourcesByOrgIDArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeResourceService) ResourcesByOrgIDReturns(result1 *types.ResourceList, result2 error) {
	fake.resourcesByOrgIDMutex.Lock()
	defer fake.resourcesByOrgIDMutex.Unlock()
	fake.ResourcesByOrgIDStub = nil
	fake.resourcesByOrgIDReturns = struct {
		result1 *types.ResourceList
		result2 error
	}{result1, result2}
}

func (fake *FakeResourceService) ResourcesByOrgIDReturnsOnCall(i int, result1 *types.ResourceList, result2 error) {
	fake.resourcesByOrgIDMutex.Lock()
	defer fake.resourcesByOrgIDMutex.Unlock()
	fake.ResourcesByOrgIDStub = nil
	if fake.resourcesByOrgIDReturnsOnCall == nil {
		fake.resourcesByOrgIDReturnsOnCall = make(map[int]struct {
			result1 *types.ResourceList
			result2 error
		})
	}
	fake.resourcesByOrgIDReturnsOnCall[i] = struct {
		result1 *types.ResourceList
		result2 error
	}{result1, result2}
}

func (fake *FakeResourceService) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.resourceContentMutex.RLock()
	defer fake.resourceContentMutex.RUnlock()
	fake.resourcesMutex.RLock()
	defer fake.resourcesMutex.RUnlock()
	fake.resourcesByClusterMutex.RLock()
	defer fake.resourcesByClusterMutex.RUnlock()
	fake.resourcesByOrgIDMutex.RLock()
	defer fake.resourcesByOrgIDMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeResourceService) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ resources.ResourceService = new(FakeResourceService)
